### ISSUE TITLE
Crashes when changing color theme

### ISSUE THREAD

**Issue by eboye** [MiMillieuh/Photoshop-CC2021-Linux#15]
Preferences > Interface > Appearance > Color Theme

Clicking on any colored box preset crashes photoshop

Otherwise it seem to be working on Manjaro linux.

**Comment by MiMillieuh** [comment]
Hello, 

it's an since the beginning of this project.

It's not really a priority, I'm focusing on getting PS2022 working and fixing issue that make PS2021 not usable.

Thanks for your report it still help a lot.

I'll close this issue it will eventually be fixed in new release if I find how.

**Comment by NyaomiDEV** [comment]
Since this issue is still present and there's no work on CC 2022, I advise you to reopen this ticket.
